dist: xenial
language: python
python:
- 3.7.2
install:
- pip install -r requirements.txt
script:
- python src/manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_19fabbf9472d_key -iv $encrypted_19fabbf9472d_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
